title: Semantic Web representations of ISO/TC 211 Geographic information/Geomatics standards
title_html: Semantic Web representations of ISO/TC 211 Geographic information/Geomatics standards

author: "ISO/TC 211"
email: nick@kurrawong.ai

font_awesome_kit_url: https://kit.fontawesome.com/77a8a07e0a.js

resource_listings:
  ontologies:
    index_url: 'ontologies'
    index_title: "Ontologies"
    resource_root: 'ontologies'
    resource_label: "ontology"

description: >-
  The repository for the def.isotc211.org website and Semantic Web namespace used by ISO/TC 211 Geographic information/Geomatics for the Semantic Web representations of standards 

tagline: >-
  Semantic Web forms of geographic standards information

# Build settings
markdown: kramdown

theme: jekyll-theme-isotc211

committee:
  id: 211
  name: Geographic information/Geomatics
  home: https://committee.iso.org/home/tc211

collections:
  pages:
    output: true
    permalink: /:path/

footer_nav:
  - url: https://committee.iso.org/home/tc211
    title: Committee Site

social:
  links:
    - url: https://twitter.com/ISOTC211
    - url: https://github.com/ISO-TC211
    - url: https://www.facebook.com/groups/236669159734679/
    - url: https://www.linkedin.com/groups/4222374

powered_by:
  url: https://open.ribose.com
  title: Ribose
  logo_path: /assets/logo-ribose.svg

source: build_source
include:
  - build_source

exclude:
  - build_source
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

plugins:
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from